/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import cars.fleet;
import cars.information;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akankshatelagamsetty
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    fleet carfleet;
    ArrayList<information> filtered;
    public SearchJPanel(fleet carfleet) {
        initComponents();
         this.carfleet= carfleet;
         filtered = carfleet.getCarfleet();
         populate(this.carfleet.getCarfleet());
         
         txtLastFormatted.setText(carfleet.getUpdatedtime());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();
        txtManufacturerSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSeatsSearch = new javax.swing.JTextField();
        txtModelNoSearch = new javax.swing.JTextField();
        txtCitySearch = new javax.swing.JTextField();
        txtExpirationYearSearch = new javax.swing.JTextField();
        txtManufacturingYearSearch = new javax.swing.JTextField();
        txtAvailabilitySearch = new javax.swing.JTextField();
        txtSerialNoSearch = new javax.swing.JTextField();
        btnSearchManufacturer = new javax.swing.JButton();
        btnModelNo = new javax.swing.JButton();
        btnSerialNo = new javax.swing.JButton();
        btnSeatsSearch = new javax.swing.JButton();
        btnExpiration = new javax.swing.JButton();
        btnManufacturingYear = new javax.swing.JButton();
        btnCity = new javax.swing.JButton();
        btnAvailabilitySearch = new javax.swing.JButton();
        txtLastFormatted = new javax.swing.JFormattedTextField();
        lblFormatted = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setBackground(new java.awt.Color(204, 204, 255));

        tblRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S. no", "Manufacturer", "Seats", "Model No", "City", "Availability", "Certificate Expiration", "Year of Manufacture"
            }
        ));
        tblRecord.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblRecord);

        txtManufacturerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerSearchActionPerformed(evt);
            }
        });
        txtManufacturerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtManufacturerSearchKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Search Cars");

        btnSearchManufacturer.setText("Search Manufacturer");
        btnSearchManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManufacturerActionPerformed(evt);
            }
        });

        btnModelNo.setText("Search Model No");
        btnModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNoActionPerformed(evt);
            }
        });

        btnSerialNo.setText("Search Serial No");
        btnSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNoActionPerformed(evt);
            }
        });

        btnSeatsSearch.setText("Search Seats");
        btnSeatsSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsSearchActionPerformed(evt);
            }
        });

        btnExpiration.setText("Search Expiration ");
        btnExpiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpirationActionPerformed(evt);
            }
        });

        btnManufacturingYear.setText("Search Manufacturing Year");
        btnManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturingYearActionPerformed(evt);
            }
        });

        btnCity.setText("Search City");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });

        btnAvailabilitySearch.setText("Search Availability");
        btnAvailabilitySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailabilitySearchActionPerformed(evt);
            }
        });

        txtLastFormatted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastFormattedActionPerformed(evt);
            }
        });

        lblFormatted.setText("Last Formatted");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearchManufacturer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtManufacturerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnModelNo)
                                    .addComponent(btnSeatsSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtModelNoSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtSeatsSearch)
                                    .addComponent(txtCitySearch))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSerialNo)
                                    .addComponent(btnExpiration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAvailabilitySearch))
                            .addComponent(btnManufacturingYear))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExpirationYearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSerialNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAvailabilitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtManufacturingYearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFormatted)
                .addGap(18, 18, 18)
                .addComponent(txtLastFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormatted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManufacturerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchManufacturer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModelNo)
                            .addComponent(txtModelNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeatsSearch)
                            .addComponent(txtSeatsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCity)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSerialNo)
                                    .addComponent(txtSerialNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExpiration))
                            .addComponent(txtExpirationYearSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManufacturingYear)
                            .addComponent(txtManufacturingYearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAvailabilitySearch)
                            .addComponent(txtAvailabilitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Search(int index, String text){
        
        ArrayList<information> temp = new ArrayList<information>();
         
        
        //String text = txtSerialNoSearch.getText().toLowerCase(); 
        for(information i : filtered){String column = "";
                if(index == 0)
                    column = i.getSerialno().toLowerCase();
                else if(index == 1)
                column = i.getManufacturer().toLowerCase();
            else if(index==2)
                column =String.valueOf(i.getSeats());
            
            else if(index==3)
                column = i.getModelno().toLowerCase();
            else if(index==4)
                column =i.getCity().toLowerCase();
            else if(index==5)
                column = i.getAvailabilty().toLowerCase();
            else if(index==6)
                column = i.getExpiration().toLowerCase();
            else if(index==7)
                column = i.getYom().toLowerCase();
            if(column.equals(text)){
                temp.add(i);
            }}
        
        filtered=temp;
        populate(temp);
    }
    
    

    
    
    
    
    private void txtManufacturerSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufacturerSearchKeyPressed
        // TODO add your handling code here:
        //Search(1,txtManufacturerSearch.getText().toLowerCase() );
        
    }//GEN-LAST:event_txtManufacturerSearchKeyPressed

    private void txtManufacturerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerSearchActionPerformed

    private void btnSearchManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManufacturerActionPerformed
        // TODO add your handling code here:
        Search(1,txtManufacturerSearch.getText().toLowerCase() );
        
    }//GEN-LAST:event_btnSearchManufacturerActionPerformed

    private void btnSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNoActionPerformed
        // TODO add your handling code here:
        Search(0,txtSerialNoSearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnSerialNoActionPerformed

    private void btnSeatsSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsSearchActionPerformed
        // TODO add your handling code here:
        Search(2,txtSeatsSearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnSeatsSearchActionPerformed

    private void btnModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNoActionPerformed
        // TODO add your handling code here:
        Search(3,txtModelNoSearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnModelNoActionPerformed

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        // TODO add your handling code here:
        Search(4,txtCitySearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnCityActionPerformed

    private void btnAvailabilitySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailabilitySearchActionPerformed
        // TODO add your handling code here:
        Search(5,txtAvailabilitySearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnAvailabilitySearchActionPerformed

    private void btnExpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpirationActionPerformed
        // TODO add your handling code here:
        Search(6,txtExpirationYearSearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnExpirationActionPerformed

    private void btnManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturingYearActionPerformed
        // TODO add your handling code here:
        Search(7,txtManufacturingYearSearch.getText().toLowerCase() );
    }//GEN-LAST:event_btnManufacturingYearActionPerformed

    private void txtLastFormattedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastFormattedActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtLastFormattedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailabilitySearch;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnExpiration;
    private javax.swing.JButton btnManufacturingYear;
    private javax.swing.JButton btnModelNo;
    private javax.swing.JButton btnSearchManufacturer;
    private javax.swing.JButton btnSeatsSearch;
    private javax.swing.JButton btnSerialNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormatted;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTable tblRecord;
    private javax.swing.JTextField txtAvailabilitySearch;
    private javax.swing.JTextField txtCitySearch;
    private javax.swing.JTextField txtExpirationYearSearch;
    private javax.swing.JFormattedTextField txtLastFormatted;
    private javax.swing.JTextField txtManufacturerSearch;
    private javax.swing.JTextField txtManufacturingYearSearch;
    private javax.swing.JTextField txtModelNoSearch;
    private javax.swing.JTextField txtSeatsSearch;
    private javax.swing.JTextField txtSerialNoSearch;
    // End of variables declaration//GEN-END:variables

    private void populate(ArrayList<information> data) {
         
        
    
    DefaultTableModel tblModel = (DefaultTableModel)tblRecord.getModel();
    tblModel.setRowCount(0);
    for(information selectedcars : data){
        Object [] row = new Object[8];
        row[0]= selectedcars;
        row[1] = selectedcars.getManufacturer();
        row[2] = selectedcars.getSeats();
        row[3] = selectedcars.getModelno();
        row[4] = selectedcars.getCity();
        row[5] = selectedcars.getAvailabilty();
        row[6] = selectedcars.getExpiration();
        row[7] = selectedcars.getYom();
        
        tblModel.addRow(row);
        
        
        
        
        
    }
    
    
    
    
    }
}
