/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import cars.fleet;
import cars.information;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akankshatelagamsetty
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    fleet carfleet;
    
    public ViewJPanel(fleet carfleet) {
        initComponents();
        this.carfleet= carfleet;
        populateTable();
        txtLastFormatted.setText(carfleet.getUpdatedtime());
        
        
    }

    ViewJPanel(information information) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtManufacturingYear = new javax.swing.JTextField();
        lblManufacturingYear = new javax.swing.JLabel();
        lblExpiration = new javax.swing.JLabel();
        txtExpiration = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        lblNodelNo = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        lblmanufacturer = new javax.swing.JLabel();
        lblSNo = new javax.swing.JLabel();
        txtSNo = new javax.swing.JTextField();
        txtLastFormatted = new javax.swing.JFormattedTextField();
        lblFormatted = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        tblRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. no", "Manufacturer", "Seats", "Model No", "City", "Availability", "Certificate Expiration", "Year of Manufacture"
            }
        ));
        tblRecord.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblRecord);

        btnUpdate.setText("Update Data");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturingYearActionPerformed(evt);
            }
        });

        lblManufacturingYear.setText("Manufactured Year");

        lblExpiration.setText("Maintenance Expiration Date(MM/YY)");

        txtExpiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpirationActionPerformed(evt);
            }
        });

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability");

        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        lblNodelNo.setText("Model No");

        lblSeats.setText("Seats");

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });

        lblmanufacturer.setText("Manufacturer");

        lblSNo.setText("S.no");

        txtSNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNoActionPerformed(evt);
            }
        });

        txtLastFormatted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastFormattedActionPerformed(evt);
            }
        });

        lblFormatted.setText("Last Formatted");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("View Car Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete)
                .addGap(47, 47, 47)
                .addComponent(lblFormatted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblManufacturingYear)
                                    .addGap(105, 105, 105)
                                    .addComponent(txtManufacturingYear))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblExpiration)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblCity)
                            .addComponent(lblNodelNo)
                            .addComponent(lblAvailability)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeats)
                                    .addComponent(lblmanufacturer)
                                    .addComponent(lblSNo))
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCity)
                                    .addComponent(txtSeats)
                                    .addComponent(txtSNo)
                                    .addComponent(txtManufacturer)
                                    .addComponent(txtModelNo)
                                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSNo)
                    .addComponent(txtSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNodelNo)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpiration)
                    .addComponent(txtExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturingYear)
                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormatted)
                            .addComponent(txtLastFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btndelete))
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        DefaultTableModel tblModel = (DefaultTableModel)tblRecord.getModel();

        if(tblRecord.getSelectedRowCount() ==1){

            String serialno = txtSNo.getText();
            String manufacturer = txtManufacturer.getText();
            String seats = txtSNo.getText();
            String modelno = txtModelNo.getText();
            String city = txtCity.getText();
            String availabiltiy = txtAvailability.getText();
            String expiration = txtExpiration.getText();
            String yom = txtManufacturingYear.getText();

            if(txtSNo.getText().equals("")||txtManufacturer.getText().equals("")||txtSeats.getText().equals("")|| txtModelNo.getText().equals("")||txtCity.getText().equals("")||txtAvailability.getText().equals("") || txtExpiration.getText().equals("") || txtManufacturingYear.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Enter All Fields");}

            else{
                tblModel.setValueAt(serialno, tblRecord.getSelectedRow(),0);
                tblModel.setValueAt(manufacturer, tblRecord.getSelectedRow(),1);
                tblModel.setValueAt(seats, tblRecord.getSelectedRow(),2);
                tblModel.setValueAt(modelno, tblRecord.getSelectedRow(),3);
                tblModel.setValueAt(city, tblRecord.getSelectedRow(),4);
                tblModel.setValueAt(availabiltiy, tblRecord.getSelectedRow(),5);
                tblModel.setValueAt(yom, tblRecord.getSelectedRow(),6);

                JOptionPane.showMessageDialog(this, "Update Successful");
            }

        } else if (tblRecord.getSelectedRowCount() ==0){
            JOptionPane.showMessageDialog(this, "Empty Table");
        }
        else{
            JOptionPane.showMessageDialog(this, "Select a single row to be updated");
        }

        // TODO add your handling code here:
 
        Date now = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String Daytime = formatter.format(now);
        carfleet.setUpdatedtime(Daytime);
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        DefaultTableModel tblModel = (DefaultTableModel)tblRecord.getModel();
        int selectedRowIndex = tblRecord.getSelectedRow();
        tblModel.removeRow(selectedRowIndex);

        //populateTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturingYearActionPerformed

    private void txtExpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpirationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpirationActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed

    private void txtSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNoActionPerformed

    private void txtLastFormattedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastFormattedActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtLastFormattedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblExpiration;
    private javax.swing.JLabel lblFormatted;
    private javax.swing.JLabel lblManufacturingYear;
    private javax.swing.JLabel lblNodelNo;
    private javax.swing.JLabel lblSNo;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblmanufacturer;
    private javax.swing.JTable tblRecord;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpiration;
    private javax.swing.JFormattedTextField txtLastFormatted;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSNo;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
    
    DefaultTableModel tblModel = (DefaultTableModel)tblRecord.getModel();
    tblModel.setRowCount(0);
    for(information selectedcars : carfleet.getCarfleet()){
        Object [] row = new Object[8];
        row[0]= selectedcars;
        row[1] = selectedcars.getManufacturer();
        row[2] = selectedcars.getSeats();
        row[3] = selectedcars.getModelno();
        row[4] = selectedcars.getCity();
        row[5] = selectedcars.getAvailabilty();
        row[6] = selectedcars.getExpiration();
        row[7] = selectedcars.getYom();
        
        tblModel.addRow(row);
        
        
        
        
        
    }
    
    
    
    }
}
